export const smallProjects = [
  {
    title: "All Nations Database",
    technologies: ["React", "CSS", "API"],
    img: "nations-api",
    link: "https://countries-data-piyush.vercel.app/",
    sourceCode: "https://github.com/immortalWebDev/Countries-data",
  },
  {
    title: "Live Image Search + AI captions",
    technologies: ["HTML", "CSS", "JavaScript","API","AI"],
    img: "ai-search",
    link: "https://spectra-search-piyush.vercel.app/",
    sourceCode: "https://github.com/immortalWebDev/vista-ai-search",
  },
  {
    title: "Movie Booking (User & Admin)",
    technologies: ["React","Firebase","Redux Toolkit"],
    img: "movie-user",
    userLink: "https://movie-user-piyush.vercel.app/",
    adminLink:"https://movie-admin-piyush.vercel.app/",
    sourceCode: "https://github.com/immortalWebDev/movie-booking-user",
  },

  {
    title: "Background Remover",
    technologies: ["HTML", "CSS", "JavaScript","API"],
    img: "bg-remover",
    link: "https://bg-remover-piyush.vercel.app/",
    sourceCode: "https://github.com/immortalWebDev/Background-remover",
  },
  {
    title: "Text Manager",
    technologies: ["HTML", "JavaScript", "CSS","NPM"],
    img: "text-manager",
    link: "https://text-master-piyush-immortalwebdevs-projects.vercel.app/",
    sourceCode: "https://github.com/immortalWebDev/Text-Master",
  },
  {
    title: "Drawing pad",
    technologies: ["JavaScript", "CSS", "HTML"],
    img: "drawing-pad",
    link: "https://drawing-pad-piyush.vercel.app/",
    sourceCode: "https://github.com/immortalWebDev/Drawing-pad",
  },
  {
    title: "Tic-Tac-Toe",
    technologies: ["React", "Bootstrap", "CSS"],
    img: "tic-tac-toe",
    link: "https://tic-tac-toe-piyush.vercel.app/",
    sourceCode: "https://github.com/immortalWebDev/Tic-tac-toe",
  },
  {
    title: "Goal setter",
    technologies: ["JavaScript", "CSS", "HTML"],
    img: "goal-setter",
    link: "https://todays-tasks-piyush.vercel.app/",
    sourceCode: "https://github.com/immortalWebDev/Todays-Tasks",
  },
  {
    title: "Analog clock",
    technologies: ["JavaScript", "HTML", "CSS"],
    img: "analog-clock",
    link: "https://analog-clock-piyush.vercel.app/",
    sourceCode: "https://github.com/immortalWebDev/Analog-Clock",
  },
  {
    title: "QR Generator",
    technologies: ["React", "Bootstrap", "CSS","API"],
    img: "qr-generator",
    link: "https://qr-generate-piyush.vercel.app/",
    sourceCode: "https://github.com/immortalWebDev/QR-Generator",
  },
  {
    title: "Captcha Generator",
    technologies: ["JavaScript", "API", "HTML"],
    img: "captcha-generator",
    link: "https://cap-gen-piyush.vercel.app/",
    sourceCode: "https://github.com/immortalWebDev/Captcha-generator",
  },
  {
    title: "Bill Splitter",
    technologies: ["JavaScript", "HTML", "CSS"],
    img: "bill-split",
    link: "https://bill-split-piyush.vercel.app/",
    sourceCode: "https://github.com/immortalWebDev/Bill-splitter",
  },

  // {
  //   title: "Random Quote Generator",
  //   technologies: ["JavaScript", "HTML", "NodeJS","API"],
  //   img: "quote-generator",
  //   link: "https://quote-generator-itu4.onrender.com",
  //   sourceCode: "https://github.com/immortalWebDev/Quote-generator",
  // },
  // {
  //   title: "Currency Converter",
  //   technologies: ["JavaScript", "API", "HTML","API"],
  //   img: "currency-converter",
  //   link: "https://cur-con-piyush.netlify.app/",
  //   sourceCode: "https://github.com/immortalWebDev/Currency-converter",
  // },
  {
    title: "Summary Generator",
    technologies: ["JavaScript", "HTML", "CSS","API"],
    img: "sum-generator",
    link: "https://sum-gen-piyush.vercel.app/",
    sourceCode: "https://github.com/immortalWebDev/Summary-generator",
  },
  {
    title: "Background color changer",
    technologies: ["JavaScript", "CSS", "HTML"],
    img: "bg-changer",
    link: "https://bg-changer-piyush.vercel.app/",
    sourceCode: "https://github.com/immortalWebDev/Background-changer",
  },
];
